[project]
name = "bots"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "patchright",
    "pydantic-settings",
    "python-dotenv",
    "camoufox[geoip]",
    "loguru",
    "pyjwt>=2.12.1",
    "cryptography>=46.0.5",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "ruff",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
